#!/bin/bash
#
#  In order to prevent test IDs overlapping with real IDs and causing potential ambiguity
#  in the audit trail, we bump all sequences to a sufficiently high value that no overlap
#  will practically occur within the expected lifetime of the application.
#

. ~/.bash_profile

sqlplus /nolog <<EOSQL
connect / as sysdba

DECLARE
   -- Ensure all new IDs are generated from 9,000,000,000 onwards as these IDs
   -- are sufficiently high as will never be reached in the live application.
   l_baseline_id CONSTANT INTEGER := 9000000000;
   l_dummy_id    INTEGER;
BEGIN
-- We ignore the OFFENDER_CRN_SEQ since test CRNs are generated by
-- changing the CRN_PREFIX in ND_PARAMETERS instead.
FOR x IN (SELECT sequence_owner,
                 sequence_name,
                 increment_by,
                 last_number
          FROM   dba_sequences
          WHERE  sequence_owner = 'DELIUS_APP_SCHEMA'
          AND    sequence_name != 'OFFENDER_CRN_SEQ'
          AND    sequence_name NOT LIKE 'Z_%')
LOOP
   -- We want to keep the existing MIN_VALUE the same as it exists in the source
   -- database, so we simply increment by a large enough value to
   -- reach the baseline value
   IF l_baseline_id-x.last_number > 0
   THEN
       IF x.sequence_name = 'SYSTEM_USER_ID_SEQ'
       THEN
          -- Special case for System Users as these are capped at a smaller maximum value than other sequences
          EXECUTE IMMEDIATE 'ALTER SEQUENCE delius_app_schema.system_user_id_seq INCREMENT BY '||(9999000-x.last_number);
       ELSE     
          EXECUTE IMMEDIATE 'ALTER SEQUENCE '||x.sequence_owner||'.'||x.sequence_name||
                             ' INCREMENT BY '||(l_baseline_id-x.last_number);
       END IF;
       -- Get next value to force incrementing
       EXECUTE IMMEDIATE 'SELECT '||x.sequence_owner||'.'||x.sequence_name||'.NEXTVAL FROM DUAL'
       INTO l_dummy_id;
       -- Now reset to the previous increment by
       EXECUTE IMMEDIATE 'ALTER SEQUENCE '||x.sequence_owner||'.'||x.sequence_name||
                         ' INCREMENT BY '||x.increment_by;
   END IF;
END LOOP;
END;
/
EXIT
EOSQL
   
   
