#!/bin/bash

. ~/.bash_profile

sqlplus -s /  as sysdba <<EOF
WHENEVER SQLERROR EXIT FAILURE;
SET FEEDBACK OFF
SET HEADING OFF
SET SERVEROUT ON
SET PAGES 0

SELECT LTRIM(TIMESTAMP_TO_SCN(TO_TIMESTAMP('${RESTORE_DATE_TIME}','DD-MM-YYYY-HH24-MI-SS')))
FROM dual;

EOF