#!/bin/bash

. ~/.bash_profile

DB_USER="SYS\$UMF"
DB_PASS="${1}"

sqlplus -s / as sysdba << EOF

SET LINES 132
SET PAGES 0
SET FEEDBACK OFF
SET HEADING OFF
WHENEVER SQLERROR EXIT FAILURE;

ALTER USER ${DB_USER} ACCOUNT UNLOCK;
ALTER USER ${DB_USER} IDENTIFIED BY ${DB_PASS};

EXIT
EOF