- block:
    - name: Check if RMAN_CATALOG Profile Exists
      script: ../../all_password_rotation/files/get_database_profile.sh
      register: get_rman_catalog_profile
      changed_when: false
      environment:
        PROFILE_NAME: "RMAN_CATALOG_PROFILE"

    # Check Which Profile RCVCATOWNER is Using
    - name: Check Current RCVCATOWNER Profile
      script: ../../all_password_rotation/files/get_current_profile.sh
      register: get_rcvcatowner_current_profile
      changed_when: false
      environment:
        PROFILE_USER: "RCVCATOWNER"

    - debug:
        var: get_rman_catalog_profile

    - name: Create RMAN_CATALOG Profile
      script: ../../all_password_rotation/files/create_database_profile.sh
      register: out
      when: get_rman_catalog_profile.stdout_lines[-1] != 'RMAN_CATALOG_PROFILE'
      environment:
        PROFILE_NAME: "RMAN_CATALOG_PROFILE"


    - debug:
        var: get_rcvcatowner_current_profile

    - name: Set RCVCATOWNER Profile
      script: ../../all_password_rotation/files/set_database_profile.sh
      when: get_rcvcatowner_current_profile.stdout_lines[-1] != 'RMAN_CATALOG_PROFILE'
      environment:
        PROFILE_USER: "RCVCATOWNER"
        PROFILE_NAME: "RMAN_CATALOG_PROFILE"

  environment:
    OEM_DB_NAME: "{{ db_configs['RCVCAT']['rcvcat_db_name'] }}"
