name: "Oracle: Audit Purge GET_EXTRACTS_DATA"
run-name: "Oracle: ${{ github.event.inputs.TargetEnvironment }}-audit-purge-get-extracts-data"
on:
  workflow_dispatch:
    inputs:
      # Note that we use, for example, "dev" here instead of "delius-core-dev"
      # since we need to include both Delius & MIS environments in the same rollback.
      TargetEnvironment:
        description: "Target environment"
        required: true
        type: choice
        options:
          - "dev"
          - "test"
          - "training"
          - "stage"
          - "preprod"
          - "prod"
      SourceCodeVersion:
        description: "Source version for the hmpps-delius-operation-automation. Enter a pull request, branch, commit ID, tag, or reference."
        type: string
        default: "main"
      SourceConfigVersion:
        description: "Source version for the modernisation-platform-configuration-management. Enter a pull request, branch, commit ID, tag, or reference."
        type: string
        default: "main"

env:
  ansible_config: operations/playbooks/ansible.cfg
  command: ansible-playbook operations/playbooks/oracle_db_audit_purge_get_extracts_data/playbook.yml
  inventory: inventory/ansible

# Allow permissions on repository and docker image and OIDC token
permissions:
  contents: read
  packages: read
  id-token: write

jobs:          
  validate-parameters:
    environment: delius-core-dev-preapproved # Choose any environment as its only used for validating parameters
    runs-on: ubuntu-latest
    outputs:
      MisTargets: ${{ steps.mis_exists.outputs.mis_targets }}
    continue-on-error: false
    steps:

      - name: Checkout modernisation-platform-configuration-management
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: ministryofjustice/modernisation-platform-configuration-management
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            ansible/hosts
            ansible/group_vars
          path: inventory
          ref: ${{ github.event.inputs.SourceConfigVersion }}
          fetch-depth: 0

      - name: Check MIS Exists In Environment
        id: mis_exists
        working-directory: ${{ env.inventory }}
        run: |
          environment_name=environment_name_delius_mis_$(echo ${{ github.event.inputs.TargetEnvironment }} | sed 's/dev/development_dev/;s/test/test_test/;s/training/test_training/;s/stage/preproduction_stage/;s/^preprod$/preproduction_preprod/;s/^prod$/production_prod/')
          # Only required to check if mis_primarydb.yml Ansible inventory group vars file exists
          # to check MIS is in this environment
          if [[ -e group_vars/${environment_name}_mis_primarydb.yml ]]
          then
            mis_targets=${environment_name}_mis_primarydb
          else
            mis_targets=none
          fi
          echo "mis_targets=${mis_targets}" >> $GITHUB_OUTPUT

  audit-purge-delius:
    needs: validate-parameters
    environment: delius-core-${{ github.event.inputs.TargetEnvironment }}-preapproved
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ministryofjustice/hmpps-delius-operational-automation:0.80.0
    timeout-minutes: 1440
    continue-on-error: false
    outputs:
      next_partition_high_value: ${{ steps.ansible_delius.outputs.next_partition_high_value }}
      delius_rows_removed: ${{ steps.ansible_delius.outputs.delius_rows_removed }}
    steps:

      - name: Checkout hmpps-delius-operation-automation
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            playbooks/oracle_db_audit_purge_get_extracts_data
            playbooks/ansible.cfg
            common/*
          path: operations
          ref: ${{ github.event.inputs.SourceCodeVersion }}
          fetch-depth: 0

      - name: Checkout modernisation-platform-configuration-management
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: ministryofjustice/modernisation-platform-configuration-management
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            ansible/hosts
            ansible/group_vars
          path: inventory
          ref: ${{ github.event.inputs.SourceConfigVersion }}
          fetch-depth: 0

      - name: Define Delius Targets
        id: definetargets
        shell: bash
        run: |
          source "$PWD/operations/common/files/build_inventory_name.sh"
          delius_target_primary="$(build_inventory_name "delius-core-${{ github.event.inputs.TargetEnvironment }}" "_delius_standbydb1")"
          echo "delius_target_primary=${delius_target_primary}" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        id: login-aws
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: "arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/modernisation-platform-oidc-cicd"
          role-session-name: "hmpps-delius-operational-automation-${{ github.run_number }}"
          aws-region: "eu-west-2"
          role-duration-seconds: 21600

      - name: Start Ansible Audit Purge for Delius
        id: ansible_delius
        shell: bash
        run: |
          set -o pipefail
          export ANSIBLE_CONFIG=$ansible_config
          $command -i $inventory \
            -e ansible_aws_ssm_bucket_name=${{ vars.ANSIBLE_AWS_SSM_BUCKET_NAME }} \
            -e target_hosts=${{ steps.definetargets.outputs.delius_target_primary }} \
            -e delius_target_primary=${{ steps.definetargets.outputs.delius_target_primary }} \
            | tee /tmp/ansible_delius.log
          next_partition_high_value=$(cat /tmp/next_partition_high_value 2>/dev/null | tr -d '\n')
          echo "next_partition_high_value=${next_partition_high_value}" >> $GITHUB_OUTPUT
          delius_rows_removed=$(cat /tmp/delius_rows_removed 2>/dev/null | tr -d '\n')
          echo "delius_rows_removed=${delius_rows_removed}" >> $GITHUB_OUTPUT

  audit-purge-mis:
    needs: [validate-parameters,audit-purge-delius]
    if: ${{ needs.validate-parameters.outputs.MisTargets != 'none' }}
    environment: delius-mis-${{ github.event.inputs.TargetEnvironment }}-preapproved
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ministryofjustice/hmpps-delius-operational-automation:0.80.0
    timeout-minutes: 1440
    continue-on-error: false
    steps:

      - name: Checkout modernisation-platform-configuration-management
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: ministryofjustice/modernisation-platform-configuration-management
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            ansible/hosts
            ansible/group_vars
          path: inventory
          ref: ${{ github.event.inputs.SourceConfigVersion }}
          fetch-depth: 0
  
      - name: Checkout hmpps-delius-operation-automation
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            playbooks/oracle_db_audit_purge_get_extracts_data
            playbooks/ansible.cfg
            common/*
          path: operations
          ref: ${{ github.event.inputs.SourceCodeVersion }}
          fetch-depth: 0

      - name: Configure AWS Credentials
        id: login-aws
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: "arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/modernisation-platform-oidc-cicd"
          role-session-name: "hmpps-delius-operational-automation-${{ github.run_number }}"
          role-duration-seconds: 21600
          aws-region: "eu-west-2"

      - name: Start Audit Purge for MIS
        shell: bash
        run: |
          export ANSIBLE_CONFIG=$ansible_config
          $command -i $inventory \
            -e ansible_aws_ssm_bucket_name=${{ vars.ANSIBLE_AWS_SSM_BUCKET_NAME }} \
            -e target_hosts=${{ needs.validate-parameters.outputs.MisTargets }} \
            -e next_partition_high_value=${{ needs.audit-purge-delius.outputs.next_partition_high_value }} \
            -e delius_rows_removed=${{ needs.audit-purge-delius.outputs.delius_rows_removed }}